### ISSUE TITLE
More than 1000 records

### ISSUE THREAD

**Issue by rafaela-anjosbarbosa** [SAP/python-pyodata#101]
I'm using pyodata to get data from odata service but but I'm getting only the first 1000 records. help me how to get it:

```
count = theservice.entity_sets.Resources.get_entities().count().execute()
print(count)

7909
```

**BUT**

```
recursos = theservice.entity_sets.Resources.get_entities().skip(100).top(8000).execute()
df2_recursos = pd.DataFrame(columns=['ResourceId', 'ResourceEmailAddress','ResourceName'])
for i,recurso in enumerate(recursos):
        df2_recursos.loc[i] = {'ResourceId': recurso.ResourceId, 'ResourceEmailAddress': recurso.ResourceEmailAddress, 'ResourceName': recurso.ResourceName}

df2_recursos.shape

(1000, 3)
```

**Comment by filak-sap** [comment]
Hi @rafaela-anjosbarbosa , what is the output without skip() and top()?

**Comment by rafaela-anjosbarbosa** [comment]
> Hi @rafaela-anjosbarbosa , what is the output without skip() and top()?

```
recursos = theservice.entity_sets.Resources.get_entities().execute()
df2_recursos = pd.DataFrame(columns=['ResourceId', 'ResourceEmailAddress','ResourceName'])
for i,recurso in enumerate(recursos):
    df2_recursos.loc[i] = {'ResourceId': recurso.ResourceId, 'ResourceEmailAddress': recurso.ResourceEmailAddress, 'ResourceName': recurso.ResourceName}
df2_recursos.shape
(1000, 3)
```

**Comment by filak-sap** [comment]
Interesting. Thank you very much.

I have just pushed some improvements to pyodata logging.

Do you think you can reproduce the request you made in your python code with bin/pyodata? The following example demonstrates how to use it to get the EntitySet Customer from the service https://services.odata.org/V2/Northwind/Northwind.svc/

```
cd python-pyodata
PYTHONPATH=. bin/pyodata -v https://services.odata.org/V2/Northwind/Northwind.svc/ ENTITY_SET Customers
```

The output should be the following:

```
[Initializing HTTP session ...]
[Fetching $metadata ...]
INFO:pyodata.client:Fetching metadata
INFO:pyodata.client:Creating OData Schema (version: 2)
INFO:pyodata.client:Creating OData Service (version: 2)
INFO:pyodata.service:Fetched 20 entities
K CustomerID = ALFKI
+ ContactTitle = Sales Representative
+ Country = Germany
+ ContactName = Maria Anders
+ CompanyName = Alfreds Futterkiste
+ Region = 
+ City = Berlin
+ Fax = 030-0076545
+ Phone = 030-0074321
+ PostalCode = 12209
+ Address = Obere Str. 57
--------------------------------------------------------------------------------
...
```

Where we are interested in the line `INFO:pyodata.service:Fetched 20 entities` (don't forget that I have added the logging part in the last commit which I pushed few moments ago).

**Comment by filak-sap** [comment]
I am afraid that your service just refuses to send more than 1000 records, hence you probably need to fetch the entire entity set per partes:

```python
count = theservice.entity_sets.Resources.get_entities().count().execute()
skip = 100
top = 1000
start = 0
df2_recursos = pd.DataFrame(columns=['ResourceId', 'ResourceEmailAddress','ResourceName'])

while skip < count:
    recursos = theservice.entity_sets.Resources.get_entities().skip(skip).top(top).execute()
    for i,recurso in enumerate(recursos, start=start):
        df2_recursos.loc[i] = {'ResourceId': recurso.ResourceId, 'ResourceEmailAddress':   recurso.ResourceEmailAddress, 'ResourceName': recurso.ResourceName}
     skip = top
     top += 1000 
     start += len(recursos)
```

Something like above could work.

**Comment by rafaela-anjosbarbosa** [comment]
> Interesting. Thank you very much.
> 
> I have just pushed some improvements to pyodata logging.
> 
> Do you think you can reproduce the request you made in your python code with bin/pyodata? The following example demonstrates how to use it to get the EntitySet Customer from the service https://services.odata.org/V2/Northwind/Northwind.svc/
> 
> ```
> cd python-pyodata
> PYTHONPATH=. bin/pyodata -v https://services.odata.org/V2/Northwind/Northwind.svc/ ENTITY_SET Customers
> ```
> 
> The output should be the following:
> 
> ```
> [Initializing HTTP session ...]
> [Fetching $metadata ...]
> INFO:pyodata.client:Fetching metadata
> INFO:pyodata.client:Creating OData Schema (version: 2)
> INFO:pyodata.client:Creating OData Service (version: 2)
> INFO:pyodata.service:Fetched 20 entities
> K CustomerID = ALFKI
> + ContactTitle = Sales Representative
> + Country = Germany
> + ContactName = Maria Anders
> + CompanyName = Alfreds Futterkiste
> + Region = 
> + City = Berlin
> + Fax = 030-0076545
> + Phone = 030-0074321
> + PostalCode = 12209
> + Address = Obere Str. 57
> --------------------------------------------------------------------------------
> ...
> ```
> 
> Where we are interested in the line `INFO:pyodata.service:Fetched 20 entities` (don't forget that I have added the logging part in the last commit which I pushed few moments ago).

How to use when you need authentication?

**Comment by rafaela-anjosbarbosa** [comment]
> I am afraid that your service just refuses to send more than 1000 records, hence you probably need to fetch the entire entity set per partes:
> 
> ```python
> count = theservice.entity_sets.Resources.get_entities().count().execute()
> skip = 100
> top = 1000
> start = 0
> df2_recursos = pd.DataFrame(columns=['ResourceId', 'ResourceEmailAddress','ResourceName'])
> 
> while skip < count:
>     recursos = theservice.entity_sets.Resources.get_entities().skip(skip).top(top).execute()
>     for i,recurso in enumerate(recursos, start=start):
>         df2_recursos.loc[i] = {'ResourceId': recurso.ResourceId, 'ResourceEmailAddress':   recurso.ResourceEmailAddress, 'ResourceName': recurso.ResourceName}
>      skip = top
>      top += 1000 
>      start += len(recursos)
> ```
> 
> Something like above could work.

Same result. = (

**Comment by filak-sap** [comment]
> How to use when you need authentication?

If HTTP Basic Authentication is enough, you can add the command line parameter `--user USERNAME` and the tool will ask for password (or you can add `--password PASSWORD` but that means that the password will be stored in command history).

If you need OAuth or something else, then we cannot use bin/pyodata for debugging.

**Comment by rafaela-anjosbarbosa** [comment]
> > I am afraid that your service just refuses to send more than 1000 records, hence you probably need to fetch the entire entity set per partes:
> > ```python
> > count = theservice.entity_sets.Resources.get_entities().count().execute()
> > skip = 100
> > top = 1000
> > start = 0
> > df2_recursos = pd.DataFrame(columns=['ResourceId', 'ResourceEmailAddress','ResourceName'])
> > 
> > while skip < count:
> >     recursos = theservice.entity_sets.Resources.get_entities().skip(skip).top(top).execute()
> >     for i,recurso in enumerate(recursos, start=start):
> >         df2_recursos.loc[i] = {'ResourceId': recurso.ResourceId, 'ResourceEmailAddress':   recurso.ResourceEmailAddress, 'ResourceName': recurso.ResourceName}
> >      skip = top
> >      top += 1000 
> >      start += len(recursos)
> > ```
> > 
> > 
> > Something like above could work.
> 
> Same result. = (

It worked!
My failure to indent the code.

Thanks!

**Comment by filak-sap** [comment]
> It worked!

I tested the code with https://services.odata.org/V2/Northwind/Northwind.svc/Customers?$format=json and it turned out that the value of top must be changed.

The algorithm is the following:

```python
count = theservice.entity_sets.Resources.get_entities().count().execute()
skip = 100
top = 1000
start = 0
df2_recursos = pd.DataFrame(columns=['ResourceId', 'ResourceEmailAddress','ResourceName'])

while skip < count:
    recursos = theservice.entity_sets.Resources.get_entities().skip(skip).top(top).execute()
    for i, recurso in enumerate(recursos, start=start):
        df2_recursos.loc[i] = {'ResourceId': recurso.ResourceId, 'ResourceEmailAddress':   recurso.ResourceEmailAddress, 'ResourceName': recurso.ResourceName}
    skip += top
    start += len(recursos)
```

> My failure to indent the code.

Sorry about that. I wrote that code in my browser without testing and did some typos.
