### ISSUE TITLE
MS Dynamics 2015 use MERGE instead of PATCH

### ISSUE THREAD

**Issue by bip91** [SAP/python-pyodata#103]
Hi Filak,

To update data, MS Dynamics 2015 use MERGE method instead PATCH (Latest version are now using PATCH method).

Hack is very easy in service.py : 
`

       # pylint: disable=no-self-use
        #return 'PATCH'
        return 'MERGE'

`

But is there a way to integrate these changes in a vendor specific python file as it exists for SAP 
instead of breaking the lib ?

**Comment by filak-sap** [comment]
@bip91 Please, have a look at #112

**Comment by filak-sap** [comment]
Documented at https://pyodata.readthedocs.io/en/latest/usage/updating.html#
