### ISSUE TITLE
PyPi

### ISSUE THREAD

**Issue by kovnat** [SAP/python-pyodata#11]
Code, downloaded by pip install doesn't match with code from this repository. Because of this I had an error with checking if metadata is XML

**Comment by phanak-sap** [comment]
Hi @kovnat . 

I am unable to reproduce your problem, using the latest pyodata version 1.1.2. I have checked that the code from #8  - which solves exactly the bug you descibed - is present in both source and wheel package.

Could you please check/provide information of what package your system has by running
`pip show pyodata`

At the moment, the only two versions are 1.1.1 (before this fix) - and 1.1.2 (containing the fix).

You could also force install specified version by 
`pip install pyodata==1.1.2`

**Comment by phanak-sap** [comment]
Hi @kovnat. 
Since no additional information is provided, I am inclined to close this issue as not reproducible.

**Comment by kovnat** [comment]
Hi @phanak-sap!
Specifying version helped. Idk why I got an old one by pip. Thank you very much!
