### ISSUE TITLE
Bandit report - blacklist Using lxml.etree.parse 

### ISSUE THREAD

**Issue by phanak-sap** [SAP/python-pyodata#12]
MEDIUM, 1: blacklist: Using lxml.etree.parse to parse untrusted XML data is known to be vulnerable to XML attacks. Replace lxml.etree.parse with its defusedxml equivalent function.
Test ID: B320
Severity: MEDIUM
Confidence: HIGH
File: .\pyodata\v2\model.py 
More info: https://bandit.readthedocs.io/en/latest/blacklists/blacklist_calls.html#b313-b320-xml-bad-etree

**Comment by mamiksik** [comment]
I guess we should stick to lxml as "defusedxml.lxml is no longer supported and will be removed in a " "future release.",

**Comment by mamiksik** [comment]
Or maby we should, I think there is no other option. 
https://github.com/tiran/defusedxml/issues/38#issuecomment-488647815

but then I am confused by this: 
https://github.com/tiran/defusedxml/issues/25

**Comment by phanak-sap** [comment]
Yeah, this seems to be valid suggestion - use  `lxml.etree.iterparse(stream, schema, resolve_entities=False)`.  

The problem with this particular warning is tracked on bandit as well.
https://github.com/PyCQA/bandit/issues/435
