### ISSUE TITLE
`custom` cannot be used with `get_entity`

### ISSUE THREAD

**Issue by sephii** [SAP/python-pyodata#123]
The docs mention the following example:

```python
employee = northwind.entity_sets.Employees.get_entity(1).custom('sap-client', '100').execute()
```

Executing this results in an error: `'EntityGetRequest' object has no attribute 'custom'`. That's because the `EntityGetRequest` extends `ODataHttpRequest`, but `custom` is defined in one of its subclass, `QueryRequest`.

**Comment by filak-sap** [comment]
Thank you for taking the time to file this issue! It seems that the method `custom` should be moved the class `ODataHttpRequest`.

**Comment by filak-sap** [comment]
Closing this issue as the PR was merged.

PS:  Replacing "Fix for" with "Fix" would close this issue automatically -> https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword
