### ISSUE TITLE
Getting error as 'Instance of Client has no entity_sets as member'

### ISSUE THREAD

**Issue by sohebkm** [SAP/python-pyodata#125]
please help me with this error. refer the screenshot below.
![image](https://user-images.githubusercontent.com/6751675/90750752-e169ed00-e2f2-11ea-9b69-fb0b652ef620.png)

Odata version: V4
Code:

import requests
import requests.auth
from requests_ntlm import HttpNtlmAuth
import pyodata

// This is just the example credential
username = "example"
password = '*********'

// Good unit is the name of the entity
directorURL = 'https://odata.ca-build.com/odata/GoodUnit'

directorSession = requests.session()
directorSession.auth= HttpNtlmAuth(username,password)
directorReqData = pyodata.Client(directorURL,directorSession)

abc = directorReqData.entity_sets.GoodUnit.get_entity(1).execute()

**Comment by filak-sap** [comment]
I am terribly sorry but OData V4 hasn't been merged to the latest version of PyOData. Please, subscribe for news at https://github.com/SAP/python-pyodata/issues/39
