### ISSUE TITLE
returning response

### ISSUE THREAD

**Issue by isragal** [SAP/python-pyodata#131]
https://github.com/SAP/python-pyodata/blob/8b03265cbe653a951410d934e6bfb6bc5dd762c1/pyodata/v2/service.py#L1402

hi you have a great library, im trying to make use of it,

but my returning content has different keys inside the hash

for exmaple
i have 'value' instead of 'd'

i'ma currently monkey patching it and just returning

content = response.json()

return content

if its easy and possible i'd like to ask if you can add such an option in the conifg sending to the client
or maybe add an exeception clause returning the raw response json

Thank you:)

**Comment by jfilak** [comment]
@isragal Are you sure you have OData V2? Can you post $metadata here?

**Comment by phanak-sap** [comment]
No interaction for a month, closing directly.
Also, the respective part of Odata v2 specs is cite _"The name of the name/value pair is always "d" and the value is the JSON representation of an OData resource as described by the subsections of this document"_

https://www.odata.org/documentation/odata-version-2-0/json-format/#RepresentingEntries
