### ISSUE TITLE
Select and get values from navs

### ISSUE THREAD

**Issue by mcharalambous** [SAP/python-pyodata#133]
Lets say i have the following url:

HTTP://..../odata/v2/EmpJob?$format=json&$select=userId,businessUnit,jobTitle,location,userNav/status
If I run the URL in Postman i get the json:
`{       
"userId": "21206",
                "businessUnit": "Test",
                "jobTitle": "QA Engineer",
                "location": "1070",
                "userNav": {
                    "__metadata": {
                        "uri": "",
                        "type": "SFOData.User"
                    },
                    "status": "t"
                },
}`

so i wrote the following code: 
```
for I in client.entity_sets().EmpJob.get_entities().select('userId,businessUnit,jobTitle,costCenter,location,userNav/status'):
    print(i.userId)  # Got value successfully 
    print(i.status) # Get error AttributeErrror: 'NoneType' object has no attribute 'to_key_string'
```
How can I select and get the userNav values ?

**Comment by phanak-sap** [comment]
Hi @mcharalambous , if I see the JSON correctly, the status field is not in the root JSON, but under the userNav object. 

So I would `try i.userNav.status`

**Comment by phanak-sap** [comment]
I don't see any further communication, so expected that this is solved now.
