### ISSUE TITLE
Help needed in connecting Pyodata to SAP OData reports

### ISSUE THREAD

**Issue by Jobbos** [SAP/python-pyodata#137]
Hi Guys,

I have created Request URI's ending on '/$metadata' in SAP.  I tried reading this with the following code:

`import requests
import pyodata

SERVICE_URL = 'https://MYURL/$metadata'

session = requests.Session()
session.auth = ('MYUSERNAME', 'MYPASSWORD')
response = session.head(SERVICE_URL, headers={'x-csrf-token': 'fetch'})
token = response.headers.get('x-csrf-token', '')
session.headers.update({'x-csrf-token': token})
work_entity = pyodata.Client(SERVICE_URL, session)`

I get the following error: "HttpError: Metadata request failed, status code: 400, body"

I have no clue why it is not working, is someone able to help me with this? Thanks!

**Comment by phanak-sap** [comment]
Hi @Jobbos. 
Best to check [existing documentation,](https://github.com/SAP/python-pyodata/blob/master/docs/usage/initialization.rst#get-the-service). 

You don't explicitly write the URL with $metadata suffix, just the service url. First request for metadata parsing is under the hood in the pyodata itself and then you work with python objects.
