### ISSUE TITLE
using userID pswd to extract Odata from a secure URL

### ISSUE THREAD

**Issue by ranjitmishra** [SAP/python-pyodata#148]
I don't see an option to specify user ID and password along with URL to extract Odata. How do I specify User ID and password. I use Basic function in EXcel Odata to give USERID and PSWD, which works perfectly fine, but can this be replaced y pyodata package?  Thanks.

**Comment by phanak-sap** [comment]
Hi @ranjitmishra you need to handle this on the Requests session object level in your code. Please refer to [documentation section about initialization](https://github.com/SAP/python-pyodata/blob/master/docs/usage/initialization.rst)

**Comment by phanak-sap** [comment]
Since this issue is not actionable on our side, closing directly. Reopen with specific python code problem if still relevant.

**Comment by ranjitmishra** [comment]
Thanks.

**Comment by ranjitmishra** [comment]
> I don't see an option to specify user ID and password along with URL to extract Odata. How do I specify User ID and password. I use Basic function in EXcel Odata to give USERID and PSWD, which works perfectly fine, but can this be replaced y pyodata package? Thanks.

Thanks. It connects now.
