### ISSUE TITLE
[rl-assigned_teams-1] At least two teams (admins, members) need to be assigned to a repository

### ISSUE THREAD

**Issue by filak-sap** [SAP/python-pyodata#151]
For details please see our wiki page at https://wiki.wdf.sap.corp/wiki/display/ospodocs/Repository+Linter+Findings#RepositoryLinterFindings-AssignedTeams(rl-assigned_teams-XX)

**Comment by phanak-sap** [comment]
The two teams exists, we are compliant - "The assignment of teams seems to be correct"
