### ISSUE TITLE
[rl-vulnerability_alerts-1] Vulnerability alerts are disabled!

### ISSUE THREAD

**Issue by filak-sap** [SAP/python-pyodata#152]
For details please see our wiki page at https://wiki.wdf.sap.corp/wiki/display/ospodocs/Repository+Linter+Findings#RepositoryLinterFindings-VulnerabilityAlerts(rl-vulnerability_alerts-XX)

**Comment by phanak-sap** [comment]
dependabot is now enabled, we are compliant - "Vulnerability alerts are enabled."
