### ISSUE TITLE
Using pyodata with userID and password

### ISSUE THREAD

**Issue by ranjitmishra** [SAP/python-pyodata#160]
I want to use pyodata package for non-SAP API like https://odata.restaurant365.net/api/v2/views/SalesPayment, which requires me to pass my userID and password to access the data. I have figure out how to send ID/pswd . Appreciate a quick help.

**Comment by filak-sap** [comment]
Thank you for taking the time to create the issue. PyOData does not implement any part of HTTP protocol, PyOData relies on an external HTTP library. If you copied sample codes from the documentation, you are most probably using Python Requests. So Just initialize your Python requests session with your credentials.

The minimal example as from the documentation https://pyodata.readthedocs.io/en/latest/#basic-usage would look like this:

```python
import pyodata
import requests

SERVICE_URL = 'http://services.odata.org/V2/Northwind/Northwind.svc/'
HTTP_LIB = requests.Session()
HTTP_LIB.auth = ('SOME_USER', 'SECRET_PASSWORD')

northwind = pyodata.Client(SERVICE_URL, HTTP_LIB)

for customer in northwind.entity_sets.Customers.get_entities().execute():
    print(customer.CustomerID, customer.CompanyName)
```

**Comment by ranjitmishra** [comment]
Thanks for the explanation. Hels.
