### ISSUE TITLE
JSONDecodeError: Expecting value

### ISSUE THREAD

**Issue by ranjitmishra** [SAP/python-pyodata#162]
I can get entity set list. Then I try to get all entities by the following ---
company = clinet.entity_sets.Company.get_entities().select('companyId,name').execute()

the above piece of code fails with **"JSONDecodeError: Expecting value"** . 
Is it not getting values in the source data? MS Excel Odata works fine with this set of source data, so I would not believe that source data has any issues. Any help is greatly appreciated.

**Comment by jfilak** [comment]
Thank you for taking the time to report this issue.
Please, enable logging and provide the request and the response: https://pyodata.readthedocs.io/en/latest/usage/advanced.html#enable-logging

**Comment by ranjitmishra** [comment]
Dear Jakub,

Thanks for your kind help. The request is as below -
DEBUG:pyodata.service:*Send (execute) GET request to
https://odata.restaurant365.net/api/v2/views/%24metadata#Company/Company
<https://odata.restaurant365.net/api/v2/views/%24metadata#Company/Company>*
DEBUG:pyodata.service:  query params: {'$select': 'companyId,name'}
DEBUG:pyodata.service:  headers: {'Accept': 'application/json'}
DEBUG:urllib3.connectionpool:Resetting dropped connection:
odata.restaurant365.net
DEBUG:urllib3.connectionpool:https://odata.restaurant365.net:443 "GET
/api/v2/views/%24metadata?$select=companyId,name HTTP/1.1" 200 16107

And the response is as follows -
DEBUG:pyodata.service:Received response
DEBUG:pyodata.service:  url:
https://odata.restaurant365.net/api/v2/views/%24metadata?$select=companyId,name#Company/Company
DEBUG:pyodata.service:  headers: {'Cache-Control': 'no-cache', 'Pragma':
'no-cache', 'Content-Length': '16107', 'Content-Type': 'application/xml',
'Expires': '-1', 'Server': 'Microsoft-IIS/10.0', 'OData-Version': '4.0',
'X-AspNet-Version': '4.0.30319', 'Request-Context':
'appId=cid-v1:b3430de1-2e1a-4491-8fc8-fa8f5a9bf518', 'X-Powered-By': '
ASP.NET', 'Date': 'Thu, 15 Jul 2021 10:47:39 GMT'}
DEBUG:pyodata.service:  *status code: 200*

I have attached the full log file for your reference.

Thanks,
Ranjit
Phone - +91 971-131-7197

**Comment by ranjitmishra** [comment]
Thanks for your kind help. **The request is as below - DEBUG:pyodata.service:Send (execute) GET request to** https://odata.restaurant365.net/api/v2/views/%24metadata#Company/Company
DEBUG:pyodata.service:  query params: {'$select': 'companyId,name'}
DEBUG:pyodata.service:  headers: {'Accept': 'application/json'}
DEBUG:urllib3.connectionpool:Resetting dropped connection: odata.restaurant365.net
DEBUG:urllib3.connectionpool:https://odata.restaurant365.net:443 "GET /api/v2/views/%24metadata?$select=companyId,name HTTP/1.1" 200 16107

**And the response is as follows - DEBUG:pyodata.service:Received response**
DEBUG:pyodata.service:  url: https://odata.restaurant365.net/api/v2/views/%24metadata?$select=companyId,name#Company/Company
DEBUG:pyodata.service:  headers: {'Cache-Control': 'no-cache', 'Pragma': 'no-cache', 'Content-Length': '16107', 'Content-Type': 'application/xml', 'Expires': '-1', 'Server': 'Microsoft-IIS/10.0', 'OData-Version': '4.0', 'X-AspNet-Version': '4.0.30319', 'Request-Context': 'appId=cid-v1:b3430de1-2e1a-4491-8fc8-fa8f5a9bf518', 'X-Powered-By': 'ASP.NET', 'Date': 'Thu, 15 Jul 2021 10:47:39 GMT'}
DEBUG:pyodata.service:  status code: 200
**[myapp.log](https://github.com/SAP/python-pyodata/files/6822588/myapp.log)**

**Comment by phanak-sap** [comment]
Note, this is Odata v4 service.

snippet from provided headers: `'OData-Version': '4.0', `
metadata header `<edmx:Edmx xmlns:edmx="http://docs.oasis-open.org/odata/ns/edmx" Version="4.0">`

At the moment pyodata supports only Odata v2, watch for issue #39
