### ISSUE TITLE
Getting an EntitySetProxy

### ISSUE THREAD

**Issue by avoutsas67** [SAP/python-pyodata#165]
Hello, 

I would like reference dynamically ODATA entities. As per the tutorial one way of getting how many records an entity_set has is: 
`service.entity_sets.entity_set_name.get_entities().count().execute()`

I would like to pass the name of the entity set as a parameter and get the number of records in the given data set.  E.g.
`service.schema.entity_set('entity_set_name') `

However the above code returns and EntitySet which does not have the method get_entities(). 
Can you please explain what is the most appropriate method of getting an EntitySetProxy entity passing the name of the entity set as a parameter? 

Many thanks in advance for your help,

Achilleas

**Comment by phanak-sap** [comment]
Hi @avoutsas67 

First, `service.schema.entity_set` is traversing the service $metadata, so it make sense to not have `get_entities` there. It just gives you the service structure. 

Second, it seems to me that referencing odata entities dynamically is not covered in exposed API. Seems as enhancement request.

However, I think I was able to get the information you seek in a ugly way, by using the Python magic methods, e.g. 
`sample.entity_sets.__getattr__('entity_set_name').get_entities().count().execute()`

Is that acceptable workaround for you?

**Comment by avoutsas67** [comment]
Dear @phanak-sap,

Many thanks for the suggestion. The following code
`service.entity_sets.__getattr__('entity_set_name').get_entities().count().execute()`
does the job

Thanks for your response and prompt action. Providing an example in the documentation would be really welcome.

Many thanks for your support.

Kind regards

Achilleas
