### ISSUE TITLE
Need new release (for date range issue fix)

### ISSUE THREAD

**Issue by bneijt** [SAP/python-pyodata#176]
I'm connecting to an SAP system en running into issue #143 for which there is a fix on master via merge #149 .

However, there has not been a release since then.

What needs to be done to get a new release published with this fix?

**Comment by phanak-sap** [comment]
True that it is a long time ago. Will work on releasing 1.7.1 with the bugfixes.

(Wanted to release 1.8.0 after merging of #154 but there will be some changes and so you are right with not waiting.)

**Comment by phanak-sap** [comment]
1.7.1 including your fix released.

https://pypi.org/project/pyodata/1.7.1/
