### ISSUE TITLE
Question about response body. 

### ISSUE THREAD

**Issue by theo-ju** [SAP/python-pyodata#180]
Dear team, 

First of all, I really appreciate your effort and work on this project. 👍 
This amazing pyodata has been helping me very much and so I could reduce my work hours dramatically. Thanks again.

This is not an issue. However I was not able to find any way to get some help from you guys. So, I leave my question here for now. If it needs to be deleted, please kindly redirect me to the right page. 

I am very new at programming or coding... so please understand me if I am wrong at something. 
My question is how I can get full response object(?) or body(?) something like in the below. 

I could see from debug logger those kind of response, but I cannot retrieve any as a python object. 
Ex)
--0A0A187DFF3A6C5CDDE8E3C2DE7FF04C0
Content-Type: application/http
Content-Length: 29504
content-transfer-encoding: binary

HTTP/1.1 200 OK
Content-Type: application/json
Content-Length: 29311
dataserviceversion: 2.0
sap-metadata-last-modified: Sat, 22 Feb 2020 18:00:34 GMT
cache-control: no-store, no-cache

{"results":"blahblahblah"}
--0A0A187DFF3A6C5CDDE8E3C2DE7FF04C0--

**Comment by phanak-sap** [comment]
Hi @theo-ju , I am closing the issue because it is almost month without any interaction. If your problem persists even with the requests hooks example, please reopen the issue with more details (python code).
