### ISSUE TITLE
can we use this lib for dynamics 365 online ? question

### ISSUE THREAD

**Issue by ibrahimhalici** [SAP/python-pyodata#182]
hi there. thank you for your great project. i dont know if it is a good place for this or this is a proper question to ask but can we use pyodata for dynamics365 F&O ?
because we also have odata source and able to use it with powerbi and excel. also from SSIS. but i tried to use pyodata and it gave an error which i have no information :/ but i guess it comes from authentication problem most possible. 
thats all. i will be happy if you can answer my question. thank you for your contributions.

**Comment by phanak-sap** [comment]
Hi @ibrahimhalici - sorry, but there is no real action item on our side from your issue description.

If dynamics365  has odata V2 (not V3/V4) API, then yes you can use pyodata.
Read the docs for this project, especially about how to enable logging and go from there.  

Study the issue #119 and #126 as an example how to create issue which can be investigated, ideally reproduce locally by developers.
