### ISSUE TITLE
Cannot access entity with Edm.Binary key

### ISSUE THREAD

**Issue by inxonic** [SAP/python-pyodata#187]
Entity URL segment is generated as `EntityNameSet(BASE64)` though the server expects `EntityNameSet(binary'BASE16')`.

Reproducer:
```python
items = entity_sets.EntityNameSet.get_entities().select('Guid').top(1).execute()
print(items[0].Description)
```
Debug output [here](https://gist.githubusercontent.com/inxonic/5896e347ae68da01ab84eea734d79293/raw/6da181dcfdf76fa2fdbe9e459021a6416e503452/pyodata.debug.log).

**Comment by phanak-sap** [comment]
Thnaks, that's good.

Even better would be with metadata file, as something that can be actually run locally, for example like https://github.com/phanak-sap/pyodata-issue-files/tree/master/%23142. Feel free to add PR to that repository, with new folder  "#187" so its easy to link with this particular issue

**Comment by inxonic** [comment]
Okay, I'd like to answer this https://github.com/SAP/python-pyodata/pull/186#issuecomment-1003782959 here, as that's the more appropriate place and any effort to fix this issue probably needs a new PR.

> But correct encoding of Edm.Binary as parameters in URL should be covered as well, right?

Of course it should be correct in all components of the URL. According to [URI Conventions](https://www.odata.org/documentation/odata-version-2-0/uri-conventions/) there could be two place in the URI with value content: The _Key Value_ in the _Resource Path_ (3.1.) and _Filter System Query Option_ (4.5.). Both cases refer to the so called _Literal_, that is specific to the Primitive Data Type.

> The "binary encoding" of URL is really something to handle in the service.py module and the `ODataHttpRequest`, since URI encoding is not part of the odata metadata and odata model per se. I see it as basic separation of responsibility. Consider hypothetical possibility of supporting the same odata metadata, but with query the server with different than HTTP protocol (it is not yet existing something like this and probably never be, but let's say Odata on something like Gopher or IPFS protocol)

Full agreement on the separation of concerns, thanks for pointing that out. With that in mind, maybe it wasn't precise enough to call this an URL generation issue. Actually it's an issue with the generation of the so called _Literal_.

And I'm afraid this can't be fixed in the `ODataHttpRequest` class because its methods only ever get the URL parts as string components. They'd have to look up the data types of the contained entities again to know, how they need to be manipulated.

So for the key value the path component is fetched from https://github.com/SAP/python-pyodata/blob/21a99b50c3b1718e5b83109d6b4d944d06b7d1e5/pyodata/v2/service.py#L371-L372 which then calls `to_literal` in the `EntityClass` https://github.com/SAP/python-pyodata/blob/21a99b50c3b1718e5b83109d6b4d944d06b7d1e5/pyodata/v2/service.py#L218

The same is true for the filter value in the query component, that calls `to_literal` in the `GetEntitySetFilter` https://github.com/SAP/python-pyodata/blob/21a99b50c3b1718e5b83109d6b4d944d06b7d1e5/pyodata/v2/service.py#L990

So if anybody is ever going to specifiy OData V2 over another fancy protocol, there'd still be an adressing scheme, that would probably also refer to the type depended literals. And that makes this issue touch the model domain.
Or put in other words, if the literal shouldn't be inside the model domain, then why are the TypTraits classes and their `to_literal` methods.

**Comment by phanak-sap** [comment]
OK, "OData V2 over another fancy protocol" will probably never happen. I was trying to illustrate a point about separation,  but not stating a valid, although hypothetical requirement. My bad. So let's consider to stick OData V2 only. And with that it mind, even the only encoding/decoding strictly base64-base16 will suffice for now. 

You are also correct with all the comments about service.py:218 and service.py:990, the `ODataHttpRequest` is not that great place after all. 

So I would probably continue with #186 as currently is, by adding/modifying tests and call it a day :)

Option 2 defined there ("Values are stored in their Python native representation") seems more dangerous. The backward compatibility is a reason enough. But also (maybe I am again missing something),  in the end, there would need to be basically same difference in binary encoding for the reading of the value (e.g. generating POST body) and for the to_literal() method (generating URL key/params), as in Option 1; so in the end, option 1 with extra steps. Am I Right?

**Comment by inxonic** [comment]
> I was trying to illustrate a point about separation, but not stating a valid, although hypothetical requirement. My bad.
That's allright. I got the point.
> in the end, there would need to be basically same difference in binary encoding for the reading of the value (e.g. generating POST body) and for the to_literal() method (generating URL key/params)
Agree, so for Option 1 that means: to/from_json does nothing and to/from_literal does base64 to base16 and vice versa.
> So I would probably continue with #186
Okay, I will dig into the tests.
