### ISSUE TITLE
Add documentation on readthedocs

### ISSUE THREAD

**Issue by FedorSelitsky** [SAP/python-pyodata#19]
It would be great to publish more detailed documentation on [readthedocs](https://readthedocs.org/). It might contain description, features, usage examples and API.

Something like that:
https://tuomur-python-odata.readthedocs.io/en/latest/

**Comment by filak-sap** [comment]
Please, have a look at the PR #31

**Comment by filak-sap** [comment]
https://pyodata.readthedocs.io/
