### ISSUE TITLE
how to conntact url with a password

### ISSUE THREAD

**Issue by chinnaphani** [SAP/python-pyodata#22]
Hi,

How can i connect to the odata url with a specificed user id and password.

Regards
Phani Kumar

**Comment by FedorSelitsky** [comment]
Hi,

You can connect to the OData service with a user and password using the following code:
```python
import requests
import pyodata

SERVICE_URL = 'http://services.odata.org/V2/Northwind/Northwind.svc/'

session = requests.Session()
session.auth = ('user', 'pass')

client = pyodata.Client(SERVICE_URL, session)
```

Read more: https://2.python-requests.org/en/master/user/advanced/#session-objects

**Comment by chinnaphani** [comment]
Thank you
