### ISSUE TITLE
404 error on initial $metadata query?

### ISSUE THREAD

**Issue by rbelew** [SAP/python-pyodata#24]
hi, just starting to try to use your OData client for a Legistar service here in Oakland.

but `http://webapi.legistar.com/v1/oakland/$metadata` fails, and it seems getting this metadata is key to the rest of your library.

(note, queries like `http://webapi.legistar.com/v1/oakland/events` work as expected.)

thanks for any pointers,  Rik

**Comment by filak-sap** [comment]
Hi @rbelew, thank you for reaching out to us. Unfortunately, I regret to inform you that you are right, the python module pyodata requires Service Metadata Document [1] which must be available in `PROTOCOL://HOST/SERVICE/$metadata`. The document is used by classes from the module to build an internal representation of the service which is then used to generate URLs, convert data types and so on.

In the case you have the metadata document off-line (stored localy on your disk, created on your own or provided by the service publisher), we might be able to enhance pyodata to read also that document - in such a case, please open a new github issue with the feature request.

1: "5. Service Metadata Document" - https://www.odata.org/documentation/odata-version-2-0/overview/
