### ISSUE TITLE
EntityContainer crashes if the entity type is null, making the entire dataset unreadable

### ISSUE THREAD

**Issue by Tunneller** [SAP/python-pyodata#240]
I was unable to open a buggy OData stream. It turned out that the problem was that an entity type was null. I was able to fix by
editing class EntityContainer to explicitly trap for this, e.g.

```
        for entity_set in self._service.schema.entity_sets: 
            if not isinstance(entity_set.entity_type, NullType):
                self._entity_sets[entity_set.name] = EntitySetProxy(self._service, entity_set)
            else:
                logging.error("Warning: I am trying to ignore error in:",entity_set)
```
 
I dont know if this is the optimal approach, but it allowed me to continue parsing the rest of the data.

**Comment by phanak-sap** [comment]
Hi @Tunneller would you pls pass a sample snippet of the $metadata of the entity type and the http response leading to this problem? Or ideally, as a new test that would reproduce the problem (check existing unit test suite and create your own mock response).

**Comment by phanak-sap** [comment]
I am closing this due inactivity, if problem still persist, please reopen with additional data, as requested above.
