### ISSUE TITLE
Cannot connect to customized odata service

### ISSUE THREAD

**Issue by rogersShu** [SAP/python-pyodata#25]
I have an odata backend. https://mobiledev-sdkforandroid-integration-projcomp-service.cfapps.sap.hana.ondemand.com and when i call  client = pyodata.Client(SERVICE_URL, session) i always get PyODataModelError
This backend is No auth.
Which is generated by Web IDE.
    raise PyODataModelError('Property {} does not exist in {}'.format(proprty, entity_type.name))
pyodata.exceptions.PyODataModelError: Property ParentProjectId does not exist in Action

**Comment by mamiksik** [comment]
Thank you for taking the time to report this issue.

Unfortunately does not support type inheritance and the type Action inherits from the type Item in your metadata.

We will try to fix it ASAP.

**Comment by phanak-sap** [comment]
closing as not reproducible / not actionable +  no communication.
