### ISSUE TITLE
No result from get_entities 'to_key_string'?

### ISSUE THREAD

**Issue by xjhowxjhow** [SAP/python-pyodata#256]
Hi, I'm trying to capture the fields that are returned via postmam in this lib using this for loop, but I get this error: 

```
empjob = cliente.entity_sets.EmpJob.get_entities().select('userId,company').execute()

for i in empjob:
    print(i)
```

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
sapvenv/lib/site-packages/pyodata/v2/service.py:877), in EntityProxy.__repr__(self)
    876 def __repr__(self):
--> 877     return self._entity_key.to_key_string()

AttributeError: 'NoneType' object has no attribute 'to_key_string'
```

am I doing something wrong?

If I remove the select it only returns a tuple

```
empjob = cliente.entity_sets.EmpJob.get_entities().execute()

for i in empjob:
    print(i)

output print : (seqNumber=1L,startDate=datetime'2023-09-01T00:00:00',userId='21')

```

**Comment by phanak-sap** [comment]
Hi @xjhowxjhow,
 based on the output without select, there seems to be that the EmbJob entity does not have a property named "company". The select is just for "return some properties, not all properties"

Check out https://www.odata.org/getting-started/basic-tutorial/ for more.

If you still see this as a problem, you need to provide the $metadata document or ideally failing test (with initialization from such metadata file locally, without networking - see existing test suite).

**Comment by xjhowxjhow** [comment]
@phanak-sap  Thanks for explaining :)

**Comment by phanak-sap** [comment]
Happy to help.
