### ISSUE TITLE
Nested expands and selects

### ISSUE THREAD

**Issue by jendrikjoe** [SAP/python-pyodata#276]
Hey there everyone,

I am currently running a lot of data request with Python, and tried to get the following running but couldn't find any docs on how to do so. I would love to select on expanded entities or even expand on expanded ones. Both seem to be possible from the spec and from the Northwind example: http://services.odata.org/V4/Northwind/Northwind.svc/Customers?$select=CustomerID&$expand=Orders($select=OrderID;$expand=Order_Details($select=UnitPrice)) 
Could anyone point me to the docs on how this is possible with pyodata? Looking at the source code I tried to pass it in the expand attribute as a string like `Orders($select= OrderID)`, but that didn't work. I think the only way would be expand the expand function to actually take objects instead of string so one can infinitely nest them, but I would be happy to get everyone's take on this.

Best and thanks a lot in advance for taking the time to think about this 🤗

**Comment by phanak-sap** [comment]
Hi @jendrikjoe 

there are two points to your question:

1) example of expand usage see in tests - https://github.com/SAP/python-pyodata/blob/03bee7c0f1a73037366a20a8fdbf01190036b14d/tests/test_service_v2.py#L1538

I see this is not explain in the documentation, just in tests, so adding missing_docs flag.

2) You are using V4 Northwind endpoint, while pyodata currently supports odata V2 only. So your URL will not work anyway. 

You need to wait for V4 support here (or use different python library). If you are able to switch do nodejs, recommending sister odata-library, which is ahead in Odata V2 + V4 support - https://github.com/SAP/odata-library

**Comment by phanak-sap** [comment]
I do not see anything actionable for this issue only, so closing.
