### ISSUE TITLE
Unable to create/post record through odata service

### ISSUE THREAD

**Issue by Ikram24817** [SAP/python-pyodata#40]
I was able the read the data, but 
Tried Creating  the record in SAP Hana db using this code, but unsuccessful
```
create_request = theservice.entity_sets.STAFF.create_entity()
create_request.set(
    STAFFID = '55243',
    STAFFNAME = 'Rodert Jane',
    EMAIL = 'chhshs@gmail.com'
)
```
getting this error

----
File "C:\PythonProgram\lib\site-packages\pyodata\v2\service.py", line 1105, in create_entity_handler
    .format(self._name, response.status_code), response)
pyodata.exceptions.HttpError: HTTP POST for Entity Set STAFF failed with status code 403
---

Please help

**Comment by jfilak** [comment]
@Ikram24817 Are you sure the entityset STAFF allows posting new entities? https://en.wikipedia.org/wiki/HTTP_403

**Comment by filak-sap** [comment]
Thank you for the reply. Could you please captured SAPUI5 request in Browser Developer tools? The backend might require a $batch request.

**Comment by Ikram24817** [comment]
Thanks Jakub

here is the $batch response

--E3E049912EF8FCBC5267CEC6DCF03E760
Content-Type: multipart/mixed; boundary=E3E049912EF8FCBC5267CEC6DCF03E761
Content-Length:       639

--E3E049912EF8FCBC5267CEC6DCF03E761
Content-Type: application/http
Content-Length: 471
content-transfer-encoding: binary

HTTP/1.1 201 Created
Content-Type: application/json
location:
https://demoqq1p1943331117trial.hanatrial.ondemand.com:443/demoikpackage/demo3Prj/services/staffinfo.xsodata/STAFF(54545455)
Content-Length: 258

{"d":{"__metadata": {"type":"sap.hana.democotent.emp.STAFFType","uri":"
https://demoqq1p1943331117trial.hanatrial.ondemand.com:443/demoikpackage/demo3Prj/services/staffinfo.xsodata/STAFF(54545455)
"},"STAFFID":54545455,"STAFFNAME":"Jack","EMAIL":"hjj@jj.com"}}
--E3E049912EF8FCBC5267CEC6DCF03E761--

--E3E049912EF8FCBC5267CEC6DCF03E760--

**Comment by Ikram24817** [comment]
*Request Headers*

   1. Accept:
   multipart/mixed
   2. Accept-Encoding:
   gzip, deflate, br
   3. Accept-Language:
   en-US
   4. Connection:
   keep-alive
   5. Content-Length:
   573
   6. Content-Type:
   multipart/mixed;boundary=batch_921c-2df3-3247
   7. Cookie:
   JTENANTSESSIONID_p1941771117trial=zjg8%2BCjm4n5T88%2BK2NI%2BFmGECchZU8NT53fpvJNEr4Q%3D;
   BIGipServer~jpaas_folder~dispatcher.hanatrial.ondemand.com=!l1/WscJP7EqD2pc08AYQbXf7c9YJWqToYp5ldQn6Ugylv4UrHKzMtQy6K5jKn6DUOSvoggOBjEETeoA=;
   JSESSIONID=067F3C05FA0650C47C6764DE27B6D19DD41FE25C2CFFBA3FC8163BA8496F934A
   8. DataServiceVersion:
   2.0
   9. Host:
   webidetesting2151015-p1941771117trial.dispatcher.hanatrial.ondemand.com
   10. MaxDataServiceVersion:
   2.0
   11. Origin:

   https://webidetesting2151015-p1941771117trial.dispatcher.hanatrial.ondemand.com
   12. Referer:

   https://webidetesting2151015-p1941771117trial.dispatcher.hanatrial.ondemand.com/webapp/index.html?hc_orionpath=%2FDI_webide_di_workspace0z3pg36yn3ejfrz6%2FNewProject&neo-di-affinity=BIGipServer~jpaas_folder~disapwebide.hanatrial.ondemand.com+%21Y8mShslBUGROrvan5pxGS30xvFkQ84K3%2FvJN5E7YnLI0S7tdGIKP%2BkuhAR6jVPHnDnUII%2FcX2vZjlfY%3D&origional-url=index.html&sap-ui-appCacheBuster=..%2F&sap-ui-xx-componentPreload=off
   13. sap-cancel-on-close:
   false
   14. sap-contextid-accept:
   header
   15. User-Agent:
   Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML,
   like Gecko) Chrome/75.0.3770.142 Safari/537.36
   16. x-csrf-token:
   5AD5549B215A29428605A6FEEA72A81D
   17. ---------------
   18. *Request PayLoad*
   19. * -batch_921c-2df3-3247 Content-Type: multipart/mixed;
   boundary=changeset_0ee1-3d11-84a7 --changeset_0ee1-3d11-84a7 Content-Type:
   application/http Content-Transfer-Encoding: binary POST STAFF HTTP/1.1
   sap-contextid-accept: header Accept: application/json Accept-Language:
   en-US DataServiceVersion: 2.0 MaxDataServiceVersion: 2.0 x-csrf-token:
   44CD448A75ECC540A770587ADE0493E0 Content-Type: application/json
   Content-Length: 66 {"STAFFID":"54545466","STAFFNAME":"Jack
   123","EMAIL":"hjj@jj.com <hjj@jj.com>"} --changeset_0ee1-3d11-84a7--
   --batch_921c-2df3-3247-- *

**Comment by filak-sap** [comment]
I bet this error is caused by CSRF protection.  We should add a hint to the exception message.

Could you please try setting up your HTTP session as described at https://pyodata.readthedocs.io/en/latest/usage/creating.html

**Comment by Ikram24817** [comment]
Thanks for the reply.

The same error, still persists, after setting the HTTP session  as
described at https://pyodata.readthedocs.io/en/latest/usage/creating.html

**Comment by filak-sap** [comment]
Have you seen the following code? I am not sure because when I opened the url in browser I could not see the following code:

```
import pyodata
import requests

SERVICE_URL = 'http://example.io/TheServiceRoot/'

session = requests.Session()
response = session.head(SERVICE_URL, headers={'x-csrf-token': 'fetch'})
token = response.headers.get('x-csrf-token', '')
session.headers.update({'x-csrf-token': token})

theservice = pyodata.Client(SERVICE_URL, session)
```

If you configured pyodata this way and it does not work and you don't mind sharing your code, I would like to ask you to post your code here.

**Comment by Ikram24817** [comment]
Here is my code

from pyslet.odata2.client import Client
import pyodata
import requests
import json



SERVICE_URL = 'https://
demodb1p22222227trial.hanatrial.ondemand.com/demoikpackage/demo3Prj/services/staffinfo.xsodata
'


session = requests.Session()
response = session.head(SERVICE_URL, headers={'x-csrf-token': 'fetch'})
token = response.headers.get('x-csrf-token', '')
session.headers.update({'x-csrf-token': token})


session.auth = ('System', 'XXXXXXXX')
theservice = pyodata.Client(SERVICE_URL, session)
print(theservice.entity_sets)
employee1 = theservice.entity_sets.STAFF.get_entity(5555).execute()
print(employee1.STAFFNAME)
employees =
theservice.entity_sets.STAFF.get_entities().select('STAFFID,STAFFNAME').execute()
for employee in employees:
    print(employee.STAFFID, employee.STAFFNAME)


*++++++++++++++++++++ The code above  for reading data is perfectly fine, I
am printing the values from SAP backend*


*===================== This part is not working*

employee_data = {
    "STAFFID" : "552437",
    "STAFFNAME" : "Rodert Jane",
    "EMAIL" : "chhshs@gmail.com"
}

create_request = theservice.entity_sets.STAFF.create_entity()
create_request.set(**employee_data)

new_employee_entity = create_request.execute()


# create_request = theservice.entity_sets.STAFF.create_entity()
# create_request.set(
#     STAFFID = 552437,
#     STAFFNAME = "Rodert Jane",
#     EMAIL = "chhshs@gmail.com"
# )
#
# new_employee_entity = create_request.execute()

**Comment by filak-sap** [comment]
The code looks OK.

Can you please enable logging:

```python
import requests
import json

# BEGIN - logging
import logging

logging.basicConfig()
logging.getLogger().setLevel(0)
# END - logging

SERVICE_URL = 'https://
demodb1p22222227trial.hanatrial.ondemand.com/demoikpackage/demo3Prj/services/staffinfo.xsodata
'
```

and try to run the create entity code again, so we will see what the server complains about.

**Comment by qcdhl** [comment]
Try to move the auth before the token request, like this:

session = requests.Session()
**session.auth = ('System', 'XXXXXXXX')**

response = session.head(SERVICE_URL, headers={'x-csrf-token': 'fetch'})
token = response.headers.get('x-csrf-token', '')
session.headers.update({'x-csrf-token': token})


theservice = pyodata.Client(SERVICE_URL, session)

**Comment by filak-sap** [comment]
> Try to move the auth before the token request, like this:

Good catch! Thank you. I ma closing this issue.

@Ikram24817 Please, re-open if you need further assistance!
