### ISSUE TITLE
Permissive parser

### ISSUE THREAD

**Issue by filak-sap** [SAP/python-pyodata#43]
Currently, the $metadata parser terminates parsing for any issue it finds in the input. We need to identify non-critical problems which we can report & ignore.

We need to support 2 use cases:
- parse any $metadata with reporting problems but without termination
- strict validation of $metadata

**Comment by mamiksik** [comment]
Comments:
1. In theory we can omit missing namespaces as xpath support wildcard searching for nodes e. g. *[local-name(.) = 'Schema'].

**Comment by mamiksik** [comment]
Proposals:
1. I propose to create XPathBuilder class which will take input in a form such as this "XPathBuilder().edmx.Edmx.edmx.DataServices.edm.Schema" and then when converted to a string will generate a string containing namespaces or replace them with a wildcard. 

Namespaces are parsed: '/edmx:Edmx/edmx:DataServices/Schema'
Namesapces are not parsed: ''/*[local-name(.) = \'Edmx\']/*[local-name(.) = \'DataServices\']/*[local-name(.) = \'Schema\']''

**Comment by filak-sap** [comment]
Resolved by https://github.com/SAP/python-pyodata/pull/44
