### ISSUE TITLE
Support: Deep Entity Creation

### ISSUE THREAD

**Issue by mnemotron** [SAP/python-pyodata#48]
Hi, is it possible to request a deep entity creation?

**Comment by filak-sap** [comment]
I hope it is possible. If not, it's a bug. See:
https://pyodata.readthedocs.io/en/latest/usage/creating.html#create-an-entity-with-a-complex-type-property

**Comment by mnemotron** [comment]
I will try to request a deep entity creation with your description. But, there is a difference between an entity with an complex type and a deep entity. A complex type is flat and bound to only one entity. A deep entity contains an entity as header and several item entities linked via an association.

**Comment by hsajib-jsf** [comment]
Any update on this issue? I am trying to create multiple deep entities and associate those to one entity.
