### ISSUE TITLE
Unable to get list of keys from entity

### ISSUE THREAD

**Issue by AlexKressner** [SAP/python-pyodata#53]
How can I get all available keys for an entity? Problem is that sometimes keys are not available so I get an AttributeError. 

example:
order[0].entity_key returns the key, e.g. '005056BA7CF71ED8A99DE9B1C85DAAF6'
order[0].ZPoMaterial gives the value for the attribute material number, e.g. 'N000000004700'
Sometimes Material number is not given. I want to check for all the available attributes/keys

**Comment by filak-sap** [comment]
I am not quite sure what is the problem you are facing but I hope you can find answers in my testing tool at:
https://github.com/SAP/python-pyodata/blob/master/bin/pyodata

I am particularly unsure about the statement `Sometimes Material number is not given` because I would expect that entities of a certain EntityType have all declared properties.

**Comment by jmeisele** [comment]
@AlexKressner 

Try this, gives a lot of information about the entity set names and their respective attributes:  

  _for es in client.schema.entity_sets:
        print(es.name)

        proprties = es.entity_type.proprties()

        for prop in es.entity_type.key_proprties:
            print(f' K {prop.name}({prop.typ.name})')
            proprties.remove(prop)

        for prop in proprties:
            print(f' + {prop.name}({prop.typ.name})')

        for prop in es.entity_type.nav_proprties:
            print(f' + {prop.name}({prop.to_role.entity_type_name})')_

**Comment by jmeisele** [comment]
@AlexKressner 

Try this, gives a lot of information about the entity set names and their respective attributes:  

  for es in client.schema.entity_sets:
        print(es.name)

        proprties = es.entity_type.proprties()

        for prop in es.entity_type.key_proprties:
            print(f' K {prop.name}({prop.typ.name})')
            proprties.remove(prop)

        for prop in proprties:
            print(f' + {prop.name}({prop.typ.name})')

        for prop in es.entity_type.nav_proprties:
            print(f' + {prop.name}({prop.to_role.entity_type_name})')

**Comment by filak-sap** [comment]
Thank you, @jmeisele !

**Comment by sihemdev** [comment]
Hi  @jmeisele , 
is it possible to add this to the documentation? This is really interesting 👍
