### ISSUE TITLE
Function to delete entity?

### ISSUE THREAD

**Issue by qcdhl** [SAP/python-pyodata#54]
Is there a delete entity function?

**Comment by filak-sap** [comment]
Oops, I am sorry, we haven't need it yet, so no, pyodata lacks the delete feature. Do you want to contribute and open a PR adding support?
We need to add the wrapper function to `class EntityProxy`:
https://github.com/SAP/python-pyodata/blob/master/pyodata/v2/service.py#L679

and we need a new `class EntityDeleteRequest` inheriting from the `class ODataHttpRequest`. There are already classes from `EntityModifyRequest`, `EntityCreateRequest`, and `EntityGetRequest`.

**Comment by mamiksik** [comment]
I think the wrapper function 'delete_entity' should be added to the class EntitySetProxy rather to the EntityProxy. Are there any reasons why to separate this functionality from the rest of 'REST' functions? Also, we could do both as I see an added benefit in calling `MyInstance.delete`

**Comment by jfilak** [comment]
Correct, use `EntitySetProxy`.

**Comment by mamiksik** [comment]
@qcdhl Hi, I created PR https://github.com/SAP/python-pyodata/pull/57, which should add requested functionality to our lib. Would it be possible for you to test the new code?

**Comment by qcdhl** [comment]
@mamiksik Hi, I have tested in my system. It works. Thank you!
