### ISSUE TITLE
pyodata.exceptions.PyODataParserError: Unsupported Schema namespace - http://schemas.microsoft.com/ado/2007/05/edm

### ISSUE THREAD

**Issue by Mracobes9** [SAP/python-pyodata#56]
I have error, when i try create client: ```pyodata.exceptions.PyODataParserError: Unsupported Schema namespace - http://schemas.microsoft.com/ado/2007/05/edm```

**Comment by mamiksik** [comment]
Hi, thank you for reporting this issue. Have you tried this: https://pyodata.readthedocs.io/en/latest/usage/initialization.html#dealing-with-errors-during-parsing-metadata?

**Comment by mamiksik** [comment]
@Mracobes9 please let me know the result.

**Comment by Mracobes9** [comment]
@mamiksik it helped me. Thanks
