### ISSUE TITLE
Unable to import Policies - PIP package not up to date

### ISSUE THREAD

**Issue by MKaras93** [SAP/python-pyodata#58]
Using version `1.2.3` from `PIP`. I have a problem with accessing a specific API. I'm receiving an error:
```python
.virtualenvs/project/lib/python3.6/site-packages/pyodata/v2/model.py", line 138, in parse_type_name
    is_collection = type_name.lower().startswith('collection(') and type_name.endswith(')')
AttributeError: 'NoneType' object has no attribute 'lower'
```

In the docs I found information that this can be due to invalid metadata. I've tried to overcome the issue as advised in the docs:

```python
import pyodata
from pyodata.v2.model import PolicyFatal, PolicyWarning, PolicyIgnore, ParserError, Config
import requests

SERVICE_URL = 'http://services.odata.org/V2/Northwind/Northwind.svc/'

namespaces = {
    'edmx': 'customEdmxUrl.com',
    'edm': 'customEdmUrl.com'
}

custom_config = Config(
    xml_namespaces=namespaces,
    default_error_policy=PolicyFatal(),
    custom_error_policies={
         ParserError.ANNOTATION: PolicyWarning(),
         ParserError.ASSOCIATION: PolicyIgnore()
    })

northwind = pyodata.Client(SERVICE_URL, requests.Session(), config=custom_config)
```

The problem is that `PolicyFatal`, `PolicyWarning` and `PolicyIgnore` are not in the `model.py`, so I can't import them. Is it a bug or am I using a wrong version? I installed it from PIP, it's `pyodata 1.2.3.`

**Comment by mamiksik** [comment]
Hi, thank you for reporting this issue. We will have look into it as soon as possible.

**Comment by jfilak** [comment]
We have to update the pip package.

**Comment by amosang** [comment]
As a workaround while waiting, it is possible to install directly from GitHub, using "pip install git+https://github.com/SAP/python-pyodata.git".

**Comment by phanak-sap** [comment]
Version 1.3.0 released on pypi.
https://pypi.org/project/pyodata/1.3.0/

**Comment by filak-sap** [comment]
Thank you, @phanak-sap  for updating the package in pypi.

@MKaras93 Please, re-test and re-open if necessary.
