### ISSUE TITLE
Custom config does not allow bypassing of erroneous service metadata

### ISSUE THREAD

**Issue by amosang** [SAP/python-pyodata#67]
Hi,
I'm running off commit d218e80ed7cf5933d5391cee74eeef705b513bf1 (sourced from GitHub repo, not PyPI; on 13 Oct 2019).

My SAP service metadata appears to have errors, and I want to bypass the erroneous service metadata (I don't use those erroneous parts).

I understand that the objective of having custom config is to allow us to get around erroneous service metadata which we do not control. To achieve this purpose, is it possible to not have the system dump, but to still return the Client object?

Below is an excerpt of the error, with full source and output in attached Word document.

[GitHub Issue - Custom config does not allow bypassing of erroneous service metadata.docx](https://github.com/SAP/python-pyodata/files/3721651/GitHub.Issue.-.Custom.config.does.not.allow.bypassing.of.erroneous.service.metadata.docx)

WARNING: Ignoring qualified Annotations of RE_CN_CONTRACT_ODATA.VL_SH_REMMMNC/RESPONSIBLE
WARNING: Ignoring qualified Annotations of RE_CN_CONTRACT_ODATA.VL_SH_REMMMNC/RESPONSIBLE
WARNING: Ignoring qualified Annotations of RE_CN_CONTRACT_ODATA.VL_SH_REMMMNC/RESPONSIBLE

KeyError                                  Traceback (most recent call last)
C:\ProgramData\Anaconda3\lib\site-packages\pyodata\v2\model.py in proprty(self, value)
   2101                 try:
-> 2102                     param.local_property = etype.proprty(param.local_property_name)
   2103                 except KeyError:

C:\ProgramData\Anaconda3\lib\site-packages\pyodata\v2\model.py in proprty(self, property_name)
   1193     def proprty(self, property_name):
-> 1194         return self._properties[property_name]
   1195 

KeyError: 'Recntype'

During handling of the above exception, another exception occurred:

RuntimeError                              Traceback (most recent call last)
<ipython-input-47-7d19419f1c10> in <module>
     20 )
     21 
---> 22 service = pyodata.Client(SERVICE_URL, session, config=custom_config)

C:\ProgramData\Anaconda3\lib\site-packages\pyodata\client.py in __new__(cls, url, connection, odata_version, namespaces, config)
     57             # create model instance from received metadata
     58             logger.info('Creating OData Schema (version: %d)', odata_version)
---> 59             schema = pyodata.v2.model.MetadataBuilder(resp.content, config=config).build()
     60 
     61             # create service instance based on model we have

C:\ProgramData\Anaconda3\lib\site-packages\pyodata\v2\model.py in build(self)
   2458 
   2459         edm_schemas = xml.xpath('/edmx:Edmx/edmx:DataServices/edm:Schema', namespaces=self._config.namespaces)
-> 2460         schema = Schema.from_etree(edm_schemas, self._config)
   2461         return schema
   2462 

C:\ProgramData\Anaconda3\lib\site-packages\pyodata\v2\model.py in from_etree(schema_nodes, config)
   1168                         config.err_policy(ParserError.ANNOTATION).resolve(ex)
   1169                     else:
-> 1170                         annotation.proprty = target_proprty
   1171                         target_proprty.value_helper = annotation
   1172 

C:\ProgramData\Anaconda3\lib\site-packages\pyodata\v2\model.py in proprty(self, value)
   2103                 except KeyError:
   2104                     raise RuntimeError('{0} of {1} points to an non existing LocalDataProperty {2} of {3}'.format(
-> 2105                         param, self, param.local_property_name, etype))
   2106 
   2107     @property

RuntimeError: ValueHelperParameter(Recntype) of ValueHelper(ContractObjectData/Objid_IS) points to an non existing LocalDataProperty Recntype of EntityType(ContractObjectData)

**Comment by amosang** [comment]
To add: Here is the Metadata Document which can be used to reproduce the error. SAP Support will fix the metadata eventually. But I'm wondering if pyodata's custom config can be made more resilient when encountering similar problematic metadata documents, instead of just crashing.

[RE_CN_CONTRACT_ODATA_SRV - svc metadata document.zip](https://github.com/SAP/python-pyodata/files/3732679/RE_CN_CONTRACT_ODATA_SRV.-.svc.metadata.document.zip)

**Comment by filak-sap** [comment]
Thank you for taking the time to analyse the problem. pyodata started as a metadata validator, so that'st the reason why it always crashes on "non-complaint" parts. One of our current goals is to make pyodata configurable the way it can ignore almost all problems. However, we are in the begging - i.e. your contribution would be more than welcome.
