### ISSUE TITLE
HttpError: Metadata request did not return XML

### ISSUE THREAD

**Issue by dhutarn** [SAP/python-pyodata#7]
OS: Win 7 x64
Python 3.6.4 (v3.6.4:d48eceb, Dec 19 2017, 06:04:45) [MSC v.1900 32 bit (Intel)] on win32

Package    Version
---------- ----------
certifi    2018.11.29
chardet    3.0.4
enum34     1.1.6
idna       2.8
lxml       3.7.3
pip        19.0.3
pyodata    1.1.1
requests   2.21.0
setuptools 28.8.0
urllib3    1.24.1

Steps to reproduce:

import requests
import pyodata

client = pyodata.Client('http://services.odata.org/V4/Northwind/Northwind.svc/', requests.Session())

expected result:

A new client object

actual result:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\Workspace\PythonAPIDemo\lib\site-packages\pyodata\client.py", line 43
, in __new__
    resp)
pyodata.exceptions.HttpError: Metadata request did not return XML, MIME type: application/xml;charset=utf-8, body:
b'<?xml version="1.0" encoding="utf-8" standalone="yes"?>\r\n<edmx:Edmx Version="1.0" xmlns:edmx="http://schemas.microsoft.com/ado/2007/06/edmx">\r\n  <edmx:DataServices xmlns:m="http://schemas.microsoft.com/ado/2007/08/dataservices/metadata" m:DataServiceVersion="1.0">\r\n    <Schema Namespace="NorthwindModel" xmlns:d="http://schemas.microsoft.com/ado/2007/08/dataservices" xmlns:m="http://schemas.microsoft.com/ado/2007/08/dataservices/metadata" xmlns="http://schemas.microsoft.com/ado/2008/09/edm">\r\n      <EntityType Name="Category">...

**Comment by dhutarn** [comment]
Same error for 'http://services.odata.org/V2/Northwind/Northwind.svc/'

**Comment by jfilak** [comment]
Yep, sorry about that, I've just opened PR #8 which fixes the issue for me.

**Comment by dhutarn** [comment]
Thanks!

**Comment by filak-sap** [comment]
Sure thing! Please, keep reporting problems if you have time. We highly appreciate your efforts!
