### ISSUE TITLE
No entities loaded from metadata

### ISSUE THREAD

**Issue by GambitK** [SAP/python-pyodata#72]
I'm trying to use pyodata to read a webservice published in dynamics nav 2018. It seems to have successfully loaded the metadata but when I try to print the entites it comes up empty.

Here's the code:

```
import requests
import pyodata
from requests_ntlm import HttpNtlmAuth
from pyodata.v2.model import Config

odatav2 = 'http://localhost/testing/OData/'

namespaces = {
    'edm': 'http://localhost/testing/OData/$metadata'
}
custom_config = Config(xml_namespaces=namespaces)

session = requests.Session()
session.auth = HttpNtlmAuth('username', 'password'')

navservice = pyodata.Client(odatav2, session, config=custom_config)

for es in navservice.schema.entity_sets:
    print(es.name)

print('End of script')
```

Enclosed is the metadata as is shown in a browser. The script simply prints no entities.

[metadata.zip](https://github.com/SAP/python-pyodata/files/3779166/metadata.zip)

**Comment by filak-sap** [comment]
@GambitK Thank you for taking the time to report the issue.

I tried to parse your metadata and I found out that we do not support the used EDM schema even though the schema has been officially released by Microsoft (I see you tried to fix that issue). Therefore, I have added the commit https://github.com/SAP/python-pyodata/commit/f672e72ec7a7c521f00f93f8eb6114430aca5a65 so now I can successfully list all your EntitySets with the following command on my Linux box:

```bash
cd python-pyodata
PYTHONPATH=./ bin/pyodata --no-session-init --metadata metadata.xml MOCKURL
```

Please, pull the latest master branch and re-test. If the problem still persist, please, try to enable logging, re-test again and analyse to log results:

https://pyodata.readthedocs.io/en/latest/usage/advanced.html#enable-logging

**Comment by GambitK** [comment]
Thanks for the response. I'm running the command on my windows machine and I get this error:

```
[Loading $metadata from: metadata.xml ...]
Traceback (most recent call last):
  File ".\bin\pyodata", line 184, in <module>
    sys.exit(_main(sys.argv))
  File ".\bin\pyodata", line 175, in _main
    client = pyodata.Client(args.SERVICE_ROOT_URL, session, metadata=static_metadata, config=config)
TypeError: __new__() got an unexpected keyword argument 'metadata'
```
I tried loading the service with the changes, here is the log:

[output.txt](https://github.com/SAP/python-pyodata/files/3783698/output.txt)

**Comment by filak-sap** [comment]
I am sorry but it works for me on my Linux box and I have no Windows machine where I can test it.

I think that your Python loaded the module pyodata from system path where you have the recent PyPI pyodata package but you need to run python with pyodata form GitHub master. Make sure you added the path to the local repo directory to PYTHONPATH environment variable:

```
set PYTHONPATH=%PYTHONPATH%;C:\users\GambitK\github\python-pyodata
```

Or you can update your system package using the following command:

```
pip install -U git+https://github.com/SAP/python-pyodata
```

This is what I did on my Linux box to verify that the latest GitHub version can read your metadata:

```
$ cd /var/tmp
$ git clone https://github.com/SAP/python-pyodata.git
$ cd python-pyodata
$ PYTHONPATH=$PYTHONPATH:/var/tmp/python-pyodata bin/pyodata --no-session-init --metadata ~/Downloads/metadata.xml MOCKURL
[Loading $metadata from: /home/filak/Downloads/metadata.xml ...]
[Printing out all Entity Sets ...]
Chart_of_Accounts
 K No(Edm.String)
 + Name(Edm.String)
 ...
```

**Comment by GambitK** [comment]
Thanks, now its working. I did install with pip.

I've made a query for one of the entities and there's a response but after that there's an error message. This are the relevant logs:

DEBUG:pyodata.service:  url: http://localhost:7028/Prueba/OData/Customer_Card('1001')

```
Traceback (most recent call last):
  File "C:\temp\navodata.py", line 30, in <module>
    result = navservice.entity_sets.Customer_Card.get_entity('1001').execute()
  File "C:\Python\Python37-32\lib\site-packages\pyodata\v2\service.py", line 305, in execute
    return self._handler(response)
  File "C:\Python\Python37-32\lib\site-packages\pyodata\v2\service.py", line 1074, in get_entity_handler
    entity = response.json()['d']
KeyError: 'd'
```

What I find strange is that If I open the URL on my browser the response is an XML but on the code I see that the response is a JSON object.

**Comment by filak-sap** [comment]
Well, we should check if the response is a valid OData JSON response but that's for a new github issue. I consider this one resolved by the commit https://github.com/SAP/python-pyodata/commit/f672e72ec7a7c521f00f93f8eb6114430aca5a65

Regarding JSON vs. XML. In browser, you can get JSON by adding the URL paramter `$format=json`:
- XML (Atom): https://services.odata.org/V2/Northwind/Northwind.svc/Employees
- JSON: https://services.odata.org/V2/Northwind/Northwind.svc/Employees?$format=json

In the code, we use the header `Accept: application/json`
