### ISSUE TITLE
unable to fetch data from the next page (more than 1000 records)

### ISSUE THREAD

**Issue by asmaMdi** [SAP/python-pyodata#78]
I'm using pyodata to get data from odata service but  but I'm getting only the first 1000 records. help me how to get it.
TIA

**Comment by filak-sap** [comment]
Are you sure the service returns more entities in browser? I am not aware of any limit.
You might need to use $skip and $top parameters.
`*.get_entities().skip(1000).*`
`*.get_entities().top(2000).*`

**Comment by asmaMdi** [comment]
in the browser the service returns the first 1000 records only. and there is a link to the next page at the end. I will try  .get_entities().skip(1000).top(2000).*
Thank you for your quick reply

**Comment by asmaMdi** [comment]
Thank you. It works

**Comment by filak-sap** [comment]
@asmaMdi May I know what service have this behaviour? We have a similar problem in #101 - it would be cool if we can compile a list of services which have interna implicit limits on get entity set size.

**Comment by rettichschnidi** [comment]
@filak-sap Curia Vista, the business database of the Swiss Parlament (https://ws.parlament.ch/odata.svc) exposes this behavior and limits its responses to 1000 for some entities (e.g. MemberCommittee, MemberCommitteeHistory, MemberCouncilHistory, MemberParty)
