### ISSUE TITLE
differentiate empty date

### ISSUE THREAD

**Issue by trancyQ** [SAP/python-pyodata#79]
Hi, 
Recently i am using pyodata to retrieve backend data.

Issue is that i still receive a datetime object (2000,01,01) for a date that is empty at the backend. And i saw this is the default date set during initialization.
Is there a way to tell whether the date i received is empty or it's a real date that is 2000 jan 1st.

Thanks.

**Comment by jfilak** [comment]
Unfortunately, I cannot see any way how to differentiate between no date and 2000-01-01. Can you post the XML/JSON response from the server, please?

**Comment by trancyQ** [comment]
i am not sure that make sense to do additional post requests since we are already getting data though this pyodata. 
Will it be possible a quick fix to change the default date to a more unrealistic date like 1000-01-01 or 1900-01-01? so that anyone look at it will know it's not an actual date. just suggestion.

**Comment by trancyQ** [comment]
if no change will happen from your side, i am planning to do this.
if the date do not has a timezone information (.tzinfo) and the date is 2000-01-01, i will consider it as a default setting. Do you think this makes sense?

**Comment by jfilak** [comment]
I would go for the lowest allowed value which is:

```
Edm.DateTime
Represents date and time with values ranging from 12:00:00 midnight, January 1, 1753 A.D.
```

https://www.odata.org/documentation/odata-version-2-0/overview/

I have no idea why we used 2000-01-01 - perhaps, that's how Business gateway handles Null DateTime values.

I asked for the response from the server to see how the server handles non-set date. If I learn how server handles it, I might be able to use `None` or something more appropriate.

**Comment by jfilak** [comment]
I choose the value without thinking I guess and it make sense to change it to something less common.

**Comment by trancyQ** [comment]
Thank you. this will be very helpful.

**Comment by jfilak** [comment]
Sure, but can you please post your server response? Or at least the part where I can see what the server returns for empty date?

**Comment by filak-sap** [comment]
@trancyQ  Would it work for you to use None for empty Date. I think it is a rational value.

**Comment by rettichschnidi** [comment]
Once #189 got merged, users of this library will be able to detect missing properties and act on it - including setting a different/custom (default) time.

**Comment by rettichschnidi** [comment]
https://github.com/SAP/python-pyodata/pull/189 got merged. Proposing to close this issue.
