### ISSUE TITLE
EDM.Float not known

### ISSUE THREAD

**Issue by tschodde** [SAP/python-pyodata#81]
Hello everybody,
I'm using pyodata to read a custom odata service implemented in the SAP Salescloud. 
One of my attributes has the datatype Float and it seems, pyodata cannot handle it.
I got the following error message:

"pyodata.exceptions.PyODataModelError: Neither primitive types nor types parsed from service metadata contain requested type Edm.Float"

from the following module
  File "C:\Anaconda3\lib\site-packages\pyodata\v2\model.py", line 1009, in from_etree
    prop.typ = schema.get_type(prop.type_info)
  File "C:\Anaconda3\lib\site-packages\pyodata\v2\model.py", line 843, in get_type
    .format(type_info.name))

Can you please fix this as soon as possible? I want to use this package to migrate data from an old non SAP system into the Salescloud for our customer. 

Thanks in advance
Thorsten

**Comment by filak-sap** [comment]
Hi @tschodde , thank you very much for taking the time to report the issue.

Are you sure your service is OData V2? Edm.Float is not mentioned in V2 standard:
https://www.odata.org/documentation/odata-version-2-0/overview/

Anyways, I'm trying to get how Edm.Float values are formatted but it would be cool if you could download your data in browser with the parameter ?$format=json and submit examples of Edm.Floats here.

**Comment by tschodde** [comment]
Hi @filak-sap,
yes it is OData V2, at least to the SAP documentation. 
Here is an example for a Edm.Float value stored in our datamodel: 
"ZRemainingBudget":"3.76000000E+04"

I hope that helps.

Thanks for investigating the problem so fast! Thanks in advance!

**Comment by filak-sap** [comment]
@tschodde If you have time, please try to re-test with pyodata from my private repo and the PR branch: https://github.com/filak-sap/python-pyodata-1/tree/ghi_81_handle_floating_point_numbers

**Comment by tschodde** [comment]
@filak-sap: Thanks for the fast fix. I will try to find some time this week to test your new branch. I build in a local workaround for now, so that I can migrate the data :)
