### ISSUE TITLE
Entity Key isn't set

### ISSUE THREAD

**Issue by squeakyboots** [SAP/python-pyodata#88]
Hi! 
When using this library to query an SAP ByD OData service I get an empty entity:
![image](https://user-images.githubusercontent.com/11595454/78390641-225ea080-75a2-11ea-97f8-ba7b643a7365.png)

When I enable debugger it looks like it's getting the data I want, just not setting the entity as expected/putting it somewhere I can access (see the last debug statement, I put ** around it):
```
>>> threads = byd_client.entity_sets.BusinessPartnerCollection.get_entity('00163E0DBAC41ED7AD87562C419D1A6C').execute()
... 
DEBUG:pyodata.service:Detected single property key, adding pair ObjectID->00163E0DBAC41ED7AD87562C419D1A6C to keyproperties
INFO:pyodata.service:Getting entity BusinessPartner for key 00163E0DBAC41ED7AD87562C419D1A6C and args {}
DEBUG:pyodata.service:New instance of EntityGetRequest for last segment: BusinessPartnerCollection
DEBUG:pyodata.service:Send (execute) GET request to https://my340402.sapbydesign.com/sap/byd/odata/cust/v1/accountinfo/BusinessPartnerCollection('00163E0DBAC41ED7AD87562C419D1A6C')
DEBUG:pyodata.service:  query params: {}
DEBUG:pyodata.service:  headers: {'Accept': 'application/json'}
DEBUG:urllib3.connectionpool:https://my340402.sapbydesign.com:443 "GET /sap/byd/odata/cust/v1/accountinfo/BusinessPartnerCollection('00163E0DBAC41ED7AD87562C419D1A6C') HTTP/1.1" 200 576
DEBUG:pyodata.service:Received response
DEBUG:pyodata.service:  url: https://my340402.sapbydesign.com/sap/byd/odata/cust/v1/accountinfo/BusinessPartnerCollection('00163E0DBAC41ED7AD87562C419D1A6C')
DEBUG:pyodata.service:  headers: {'content-type': 'application/json; charset=utf-8', 'content-length': '576', 'cache-control': 'no-cache, no-store', 'dataserviceversion': '2.0', 'c4c-odata-response-time': '111  ms', 'strict-transport-security': 'max-age=31536000; includeSubDomains'}
DEBUG:pyodata.service:  status code: 200
DEBUG:pyodata.service:  body: {"d":{"results":{"__metadata":{"uri":"https://my340402.sapbydesign.com/sap/byd/odata/cust/v1/accountinfo/BusinessPartnerCollection('00163E0DBAC41ED7AD87562C419D1A6C')","type":"cust.BusinessPartner"},"ObjectID":"00163E0DBAC41ED7AD87562C419D1A6C","RoleCode":"CRM000","StartDate":"\/Date(-62135769600000)\/","EndDate":"\/Date(253402214400000)\/","InternalID":"1060169","BusinessPartnerDefaultWeb":{"__deferred":{"uri":"https://my340402.sapbydesign.com/sap/byd/odata/cust/v1/accountinfo/BusinessPartnerCollection('00163E0DBAC41ED7AD87562C419D1A6C')/BusinessPartnerDefaultWeb"}}}}}
**DEBUG:pyodata.service:New entity proxy instance of type BusinessPartner from properties: {'results': {'__metadata': {'uri': "https://my340402.sapbydesign.com/sap/byd/odata/cust/v1/accountinfo/BusinessPartnerCollection('00163E0DBAC41ED7AD87562C419D1A6C')", 'type': 'cust.BusinessPartner'}, 'ObjectID': '00163E0DBAC41ED7AD87562C419D1A6C', 'RoleCode': 'CRM000', 'StartDate': '/Date(-62135769600000)/', 'EndDate': '/Date(253402214400000)/', 'InternalID': '1060169', 'BusinessPartnerDefaultWeb': {'__deferred': {'uri': "https://my340402.sapbydesign.com/sap/byd/odata/cust/v1/accountinfo/BusinessPartnerCollection('00163E0DBAC41ED7AD87562C419D1A6C')/BusinessPartnerDefaultWeb"}}}}**
INFO:pyodata.service:Initiating property request for __len__
INFO:pyodata.service:Initiating property request for __len__
INFO:pyodata.service:Initiating property request for url
```
As a result I seem to get an error when I try to get a property from that:
```
>>> threads.InternalID
INFO:pyodata.service:Initiating property request for InternalID
Traceback (most recent call last):
  File "C:\Users\dwilliams\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pyodata\v2\service.py", line 783, in __getattr__
    return self._cache[attr]
KeyError: 'InternalID'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "C:\Users\dwilliams\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pyodata\v2\service.py", line 786, in __getattr__
    value = self.get_proprty(attr).execute()
  File "C:\Users\dwilliams\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pyodata\v2\service.py", line 847, in get_proprty
    path = urljoin(self.get_path(), name)
  File "C:\Users\dwilliams\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pyodata\v2\service.py", line 830, in get_path
    return self._entity_set._name + self._entity_key.to_key_string()  # pylint: disable=protected-access
AttributeError: 'NoneType' object has no attribute 'to_key_string'
INFO:pyodata.service:Initiating property request for __len__
INFO:pyodata.service:Initiating property request for __len__
INFO:pyodata.service:Initiating property request for url
```

If I do something like this, it sets the entity key for each entity:
```
>>> bp_coll = byd_client.entity_sets.BusinessPartnerCollection.get_entities().select('ObjectID,InternalID').execute()
>>> print(bp_coll[0].InternalID)
'NBS'
```
![image](https://user-images.githubusercontent.com/11595454/78391134-06a7ca00-75a3-11ea-8ea2-0eecb989124b.png)

Am I doing something wrong here..?

Thanks for your time and expertise,
Dan Williams

**Comment by filak-sap** [comment]
Hi @squeakyboots, thank you for taking the time to report this issue. Would it be possible to post here the service $metadata and the full response, so we can modify our code to handle ByD results and update our test suite.

**Comment by filak-sap** [comment]
Thank you very much! Can you please fetch the response with the additional URL query parameter "$format=json" because we use JSON.

**Comment by filak-sap** [comment]
The problem is that the service does not follow the OData standard and returns the entity wrapped in the JSON object "results".

You can see the correct OData response here:
https://services.odata.org/V2/Northwind/Northwind.svc/Categories(1)?$format=json

I can add a special handler for ByD but I would like to ask you to report the problem to the service provider. It would be nice if you could also mention my email address jakub.filak@sap.com.

Before I add any ad-hockery code, I have to think twice how to make it generic as much as possible.

I would like to thank you for your patience.

**Comment by squeakyboots** [comment]
Thanks Filak! I was worried it might be something like that. I'm in no rush for a solution on this and agree it would be best not to add a special handler for ByD.

I've raised an SAP incident mentioning the generated service doesn't seem to follow the OData standard by wrapping it in "results" and mentioned your email and this thread: my301795-224270/2020

Thanks so much for your time =) I'll keep you appraised of what we hear back from the provider.

**Comment by squeakyboots** [comment]
I got an update from the SAP ByDesign support team on this:
> According to developers, the following fix will be available in 2005 upgrade:
> If the Header parameter (odata-v2-strict-json-format) is passed, then the results tag will not be shown as, for Navigation or Expanded, hen it should not have results in response if header is passed as true and cardinality is 1..1.
>  
> But if cardinality is 1..n or 0..n, then it will have the results in the response.

The 2005 is the May 2020 release, which is currently applied to our test system so I was able to confirm using the header "odata-v2-strict-json-format" results in the expected behavior (and removing it resulted in the same failure as outlined above).

@filak-sap thanks for your time and input on this

**Comment by sti0** [comment]
> The 2005 is the May 2020 release, which is currently applied to our test system so I was able to confirm using the header "odata-v2-strict-json-format" results in the expected behavior (and removing it resulted in the same failure as outlined above).

 @squeakyboots I'm facing the same issue. Could you please describe how to pass the `odata-v2-strict-json-format` into the request? Thanks in advance.

**Comment by squeakyboots** [comment]
Hi @sti0 !
You set it in your session like so:
```
  session = requests.session()
  session.headers['odata-v2-strict-json-format'] = 'true'
```

**Comment by sti0** [comment]
@squeakyboots thank you so much. That work for me, too. No I'm able to query C4C data...

@filak-sap maybe this information should be posted somewhere in the docs to help others out :)
