### ISSUE TITLE
how to query parametrized collection

### ISSUE THREAD

**Issue by michalgromiec** [SAP/python-pyodata#96]
We have OData service in which one of collection requires input parameters - how we can solve it using pyodata?

Using web browser it works using collection name, parameters passed in brackets and added "/Results" at the end of URI.

**Comment by filak-sap** [comment]
How does the URL looks like in browser?
Is your parameter passing described in OData v2 specification?

**Comment by michalgromiec** [comment]
Our URL (XXXX for hiding business data...):
XXXXXXXX.XXXXX.net:XXXXX/sap/opu/odata/sap/XXXXXX-service/XXXXX-collection(XXXXClient='532023',XXXXClientTo='')/Results

**Comment by filak-sap** [comment]
Actually, you want to get a navigation property of an entity.
In your canse the navigation property is Results and the entity is `XXXXX-collection(XXXXClient='532023',XXXXClientTo='')`

```python
count = client.entity_sets.XXXXX_collection.get_entity(XXXXClient='532023',XXXXClientTo='').nav('Results')
```

**Comment by michalgromiec** [comment]
Works great, thanks for your help!

**Comment by aixi88** [comment]
> 



> Actually, you want to get a navigation property of an entity. In your canse the navigation property is Results and the entity is `XXXXX-collection(XXXXClient='532023',XXXXClientTo='')`
> 
> ```python
> count = client.entity_sets.XXXXX_collection.get_entity(XXXXClient='532023',XXXXClientTo='').nav('Results')
> ```
I have the same problem,

But I still don't understand how to get the final data through "count"?

> Actually, you want to get a navigation property of an entity. In your canse the navigation property is Results and the entity is `XXXXX-collection(XXXXClient='532023',XXXXClientTo='')`
> 
> ```python
> count = client.entity_sets.XXXXX_collection.get_entity(XXXXClient='532023',XXXXClientTo='').nav('Results')
> ```

I have the same problem,

But I still don't understand how to get the final data through "count"

**Comment by aixi88** [comment]
> Actually, you want to get a navigation property of an entity. In your canse the navigation property is Results and the entity is `XXXXX-collection(XXXXClient='532023',XXXXClientTo='')`
> 
> ```python
> count = client.entity_sets.XXXXX_collection.get_entity(XXXXClient='532023',XXXXClientTo='').nav('Results')
> ```

I have the same problem,

But I still don't understand how to get the final data through "count"
